name: Refresh DW EO Charts

on:
  schedule:
    # Runs at 9a, 12p, 3p, 6p ET on weekdays (Monday to Friday)
    - cron: "0 14,17,20,23 * * 1-5"
    # Runs at 10a ET on weekends (Saturday and Sunday)
    - cron: "0 13 * * 6,0"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::lubridate

      - name: Set up environment variables based on DATAWRAPPR secret
        run: echo "DATAWRAPPER_API_KEY=${{ secrets.DATAWRAPPER_API_KEY }}" >> $GITHUB_ENV

      - name: Install DatawRappr package
        run: |
          Rscript -e "install.packages('pak')"
          Rscript -e "pak::pkg_install('munichrocker/DatawRappr')"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run script
        run: Rscript -e 'source("update_charts.R")'
