name: Publish Datawrapper EO Charts

on:
  schedule:
    - cron: '0 14,19,00 * * *'   # 9am, 2pm, 7pm ET (14:00 UTC)
  workflow_dispatch:  # Manual trigger too for remote

jobs:
  publish-charts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("devtools")'
        Rscript -e 'devtools::install_github("munichrocker/DatawRappr")'
    - name: Run R script
      env:
        DATAWRAPPER_API_KEY: ${{ secrets.DATAWRAPPER_API_KEY }}
      run: Rscript update_charts.R