name: Publish Datawrapper EO Charts

on:
  schedule:
    - cron: '0 14,19,00 * * *'   # 9am, 2pm, 7pm ET (14:00 UTC)
  workflow_dispatch:  # Manual trigger too for remote

jobs:
  publish-charts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ runner.tool_cache }}/R
        key: ${{ runner.os }}-R-${{ hashFiles('**/*.R') }}
        restore-keys: |
          ${{ runner.os }}-R-
    - name: Install dependencies
      run: |
        Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
        Rscript -e 'if (!requireNamespace("DatawRappr", quietly = TRUE)) devtools::install_github("munichrocker/DatawRappr")'
    - name: Run R script
      env:
        DATAWRAPPER_API_KEY: ${{ secrets.DATAWRAPPER_API_KEY }}
      run: Rscript update_charts.R