name: Publish Datawrapper EO Charts

on:
  schedule:
#    - cron: '0 14,19,00 * * *'   # 9am, 2pm, 7pm ET (14:00 UTC)
  workflow_dispatch:  # Manual trigger too for remote

jobs:
  publish-charts:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'  # Specify a compatible R version
    - name: Install dependencies
      env:
        GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_github("munichrocker/DatawRappr", auth_token = Sys.getenv("GITHUB_PAT"))'
    - name: Run R script
      env:
        DATAWRAPPER_API_KEY: ${{ secrets.DATAWRAPPER_API_KEY }}
      run: Rscript update_charts.R
