name: Refresh DW EO Charts

on:
  schedule:
    - cron: "0 15,19,00 * * *" # Runs once a day at midnight (UTC)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::janitor

      - name: Set up environment variables based on DATAWRAPPR secret
        run: echo "DATAWRAPPER_API_KEY=${{ secrets.DATAWRAPPER_API_KEY }}" >> $GITHUB_ENV

      - name: Install DatawRappr package
        run: |
          Rscript -e "install.packages('pak')"
          Rscript -e "pak::pkg_install('munichrocker/DatawRappr')"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run script
        run: Rscript -e 'source("update_charts.R")'
